model:
  base_learning_rate: 1e-5   # ori: 5e-5
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    num_classes: 2   # including background
    load_only_unet: true
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "segmentation"
    cond_stage_key: "image"
    conditioning_key: "concat"
    image_size: 32
    channels: 4
    cond_stage_trainable: True    # modified
    concat_mode: True
    scale_by_std: True
    use_ema: True
    monitor: 'val_avg_dice'
    ckpt_path: "models/ldm/lsun_churches256/model.ckpt"

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8  # doubled for concat-mode
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        dropout: 0.2

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: "val/rec_loss"
        ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
        embed_dim: 4
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.2
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: #"__is_first_stage__"
      target: ldm.modules.encoders.modules.AEEncoderEmbedder
      params:
        ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
        embed_dim: 4
        double_z: True
        z_channels: 4
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        attn_resolutions: [ ]
        dropout: 0.2
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    wrap: False
    train:
      target: ldm.data.synapse.SynapseTrain
      params:
        size: 256
    validation:
      target: ldm.data.synapse.SynapseValidation
      params:
        size: 256
    test:
      target: ldm.data.synapse.SynapseValidationVolume
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False
        log_dice_frequency: 5000
        log_first_step: true


  trainer:
    benchmark: True
    check_val_every_n_epoch: 10
    accumulate_grad_batches: 1